[workspace]
authors = ["Samuel Earl <samueltremain@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "src"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.6.0.dev2025081505,<26"
